### ISSUE TITLE
ToolingUI: Design System v0.1.0

### ISSUE THREAD

**Issue by mcturco** [asyncapi/design-system#38]
# Introduction
We would like to create a system of components that can be used for the UI in [AsyncAPI Studio](https://studio.asyncapi.com/) as well as any other future UI tools that get added into the AsyncAPI org.

There should be a range of components from a tiny scale to a large scale. The visual design of the components does not need to match any specific branding, but needs to be accessible and usable. It would be best to have a neutral color palette with one accent color.

# Task List
- [ ] **Step 1:** Define - What components do we have already & what are we missing?
- [ ] **Step 2:** Ideate - Make improvements to current components & design new components
- [ ] **Step 3:** Develop - Write React components in a development environment
- [ ] **Step 4:** Test - Test components in development environment for usability
- [ ] **Step 5:** Iterate - Repeat the above steps until we are ready to release version 1
- [ ] **Step 6:** Document - Write component usage docs for both design & dev contributors

**Comment by yashsehgal** [comment]
Hey @mcturco 
Thanks for putting up this issue, would be really fun to work on this one. 😃 
I am all ready to getting started with this task.

> There should be a range of components from a tiny scale to a large scale. The visual design of the components does not need to match any specific branding, but needs to be accessible and usable. It would be best to have a neutral color palette with one accent color.

So, should we start by defining the repository structure and then we can move forward for implementing the basic properties like color palette and spacings.

Really appreciate if we can break down this issue to multiple smaller issues/tasks so that we can start building stuff. Before that we can do all the required discussions according to the `Step 01` and `Step 02` that you've mentioned.

**Comment by mcturco** [comment]
@yashsehgal Great! I believe there was one other person interested in contributing to this as well, just waiting for them to leave a comment. 

> So, should we start by defining the repository structure and then we can move forward for implementing the basic properties like color palette and spacings.

Like you said as far as having separate issues for each step, I agree and that was my initial plan. I will create the issues shortly! I think that we should start at `Step 1` and perform both a visual audit and a code audit as there could be visual inconsistencies even though the code structure might be okay. I will open an issue for that first!

**Comment by yashsehgal** [comment]
> Hey there, I am really interested in designing the UI tools, really sorry for the late reply @mcturco , will be working on it! @yashsehgal would you like to collaborate?

For sure @iipranavii 
Would love to collaborate with you on this task.
